name: Publish Release

on:
  workflow_call:
    secrets:
      PUBLISH_DOCS_TOKEN:
        required: true

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - id: get-release-version
        shell: bash
        run: ./scripts/get.sh ".version" "RELEASE_VERSION"

  publish-release-to-gh-pages:
    name: Publish DApp to `${{ needs.get-release-version.outputs.RELEASE_VERSION }}` directory of `gh-pages` branch
    needs: get-release-version
    permissions:
      contents: write
    uses: ./.github/workflows/publish-docs.yml
    with:
      destination_dir: ${{ needs.get-release-version.outputs.RELEASE_VERSION }}
    secrets:
      PUBLISH_DOCS_TOKEN: ${{ secrets.PUBLISH_DOCS_TOKEN }}

  publish-release-to-latest-gh-pages:
    name: Publish DApp to `latest` directory of `gh-pages` branch
    needs: get-release-version
    permissions:
      contents: write
    uses: ./.github/workflows/publish-docs.yml
    with:
      destination_dir: latest
    secrets:
      PUBLISH_DOCS_TOKEN: ${{ secrets.PUBLISH_DOCS_TOKEN }}
