name: Publish DApp to GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string
    secrets:
      PUBLISH_APP_TOKEN:
        required: true

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Ensure `destination_dir` is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies via Yarn
        run: yarn --immutable
      - name: Update package.json homepage field
        run: |
          sed -i 's/"homepage": ".*"/"homepage": "https:\/\/metamask.github.io\/test-dapp-mm-pay\/${{ inputs.destination_dir }}"/' package.json
      - name: Build DApp
        run: yarn build
      - name: Deploy to `${{ inputs.destination_dir }}` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935
        with:
          personal_token: ${{ secrets.PUBLISH_APP_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ inputs.destination_dir }}
